### ISSUE TITLE
/upload failed

### ISSUE THREAD

**Issue by nalakawula** [botgram/shell-bot#15]
Cool project!
I try to upload a file but encounter an error.
`/upload abc.txt`

then got error messsage:
```
Couldn't send file: sendDocument failed: Request Entity Too Large
```
abc.txt size is ~90MB

Thank you

**Comment by jmendeth** [comment]
I should probably mention this more explicitely, but unfortunately Telegram bots [can only send up to 50MB](https://github.com/botgram/botgram/blob/master/docs/reply.md#sending-in-place) :(

This has nothing to do with Botgram, it's just a limitation of Telegram's platform.

**Comment by nalakawula** [comment]
Thank you, so i must split file using zip command before upload.

**Comment by jmendeth** [comment]
Yeah, that's one way.

**Comment by hurondefuego** [comment]
Where can I find the files I upload?
