### ISSUE TITLE
multi-user support (or inline mode, so it can be used in groups)

### ISSUE THREAD

**Issue by samthelion** [botgram/shell-bot#21]
Hi, the thing is that i want to use the bot from my two telegram accounts. I would like to [either]
- setup more than one chat_id.
- use the bot in a group that i created with my accounts and the bot as members.

I suppose that the last one can only be done setting up inline mode.

Cheers!

**Comment by samthelion** [comment]
Oops... the bot commands "/grant" and/or "/token" answer my question. Though i'd still like to know about inline mode...

**Comment by mildsunrise** [comment]
what do you mean by inline mode?

**Comment by mildsunrise** [comment]
by the way, you can also configure a group as the owner

**Comment by samthelion** [comment]
> 
> 
> what do you mean by inline mode?

Well, i realized that doesn't make sense to use inline mode in this kind of bot. although for the "cd" command it would be really useful, that way we don't need to know the exact path we want to "cd" to by memory. Learn more here: https://core.telegram.org/bots/inline

**Comment by mildsunrise** [comment]
oh, you mean to use inline mode to suggest autocompletions? I'll keep this on mind, and of course, patches are welcome :)

**Comment by tshwangq** [comment]
add your telegram userid to granted array in server.js will do the trick
