### ISSUE TITLE
Add a /download command to the bot

### ISSUE THREAD

**Issue by samthelion** [botgram/shell-bot#22]
It will work similar to /upload, for example:
-user sends /download message to the bot.
-bot replies something like "Waiting for you to send a file..." or "The file will be saved to /home/user (current working dir)"
-user sends the file, photo or video
-bot replies that it is downloading and if possible will show progress.

I would do it myself if i could, but i don't know how.

Best Regards!

**Comment by mildsunrise** [comment]
This is [already](https://github.com/botgram/shell-bot/blob/a88dded6b13b0da75854475ec84ac241f4fde39d/server.js#L253) implemented :)
When the bot says «Now at: ...», reply to that message with a file and it will be saved to that folder.
You can also reply to an upload from the bot (see /upload) to overwrite that file.

**Comment by samthelion** [comment]
> 
> 
> This is [already](https://github.com/botgram/shell-bot/blob/a88dded6b13b0da75854475ec84ac241f4fde39d/server.js#L253) implemented :)
> When the bot says «Now at: ...», reply to that message with a file and it will be saved to that folder.
> You can also reply to an upload from the bot (see /upload) to overwrite that file.

Cool! I didn't knew that...
