### ISSUE TITLE
Does shell bot support webhook.

### ISSUE THREAD

**Issue by kcubeterm** [botgram/shell-bot#34]
It's a nice bot, I don't know it supports webhook or not,

**Comment by mildsunrise** [comment]
nope, botgram in general does [not support webhook](https://github.com/botgram/botgram/blob/master/docs/global.md#webhooks)

I'm curious though, why would a webhook be useful here?

**Comment by kcubeterm** [comment]
> I'm curious though, why would a webhook be useful here?

I want to deploy it on heroku.
