### ISSUE TITLE
i have pushed to heroku but bot is not responding

### ISSUE THREAD

**Issue by askfriends** [botgram/shell-bot#38]
hello;

i want to run .py in heroku, and thats why i have downloaded that file in this shell bot root folder and pushed to heroku, but when i start bot and give some commands its not responding at all.
i have edited confi.json and usd my bot token and owner id too.
so what am i missing here?

**Comment by mildsunrise** [comment]
this doesn't work with heroku, it's designed to put it in your server (the one you want to issue commands in)

**Comment by askfriends** [comment]
> this doesn't work with heroku, it's designed to put it in your server (the one you want to issue commands in)

im already using this with another bot in telegram, hosted on heroku.
