### ISSUE TITLE
Installation broken on raspberry pi os

### ISSUE THREAD

**Issue by MikkoWrightson** [botgram/shell-bot#39]
While installing on a raspberry pi I can't get over the following error. Can't find the repo it's trying to talk to manually either. I'm working on an otherwise fresh install of raspbian except I've got [Teleframe](https://github.com/LukeSkywalker92/TeleFrame) running.

Edit: I had a few raspis running both Teleframe and shell-bot at the same time in the summer. I was trying to make another one and the install keeps failing

```
26 error Error while executing:
26 error /usr/bin/git ls-remote -h -t ssh://git@github.com/botgram/node-termios.git
26 error
26 error git@github.com: Permission denied (publickey).
26 error fatal: Could not read from remote repository.
26 error
26 error Please make sure you have the correct access rights
26 error and the repository exists.
26 error
26 error exited with error code: 128
27 verbose exit [ 1, true ]
```

**Comment by mildsunrise** [comment]
just guessing, but it seems I forgot to update package-lock.json in https://github.com/botgram/shell-bot/commit/a88dded6b13b0da75854475ec84ac241f4fde39d...

**Comment by MikkoWrightson** [comment]
Hi, i actually finally got it working after a couple of hours, of course just after opening the issue. Seems like my installation of npm was broken as it started working after reinstalling it. Thanks for a quick response!:)

**Comment by mildsunrise** [comment]
no worries ^^
